# Generated by Django 4.2.1 on 2023-06-17 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item01',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseinfo')),
                ('itemName01', models.CharField(max_length=50)),
            ],
            bases=('api.baseinfo', models.Model),
        ),
        migrations.CreateModel(
            name='Item02',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseinfo')),
                ('itemName02', models.CharField(max_length=50)),
                ('itemName01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item01')),
            ],
            bases=('api.baseinfo', models.Model),
        ),
        migrations.CreateModel(
            name='Planguage',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseinfo')),
                ('langName', models.CharField(max_length=50)),
            ],
            bases=('api.baseinfo', models.Model),
        ),
        migrations.CreateModel(
            name='Item03',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseinfo')),
                ('itemName03', models.CharField(max_length=50)),
                ('itemName02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item02')),
            ],
            bases=('api.baseinfo', models.Model),
        ),
        migrations.AddField(
            model_name='item01',
            name='langName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planguage'),
        ),
        migrations.CreateModel(
            name='InfoList',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.baseinfo')),
                ('content', models.CharField(max_length=1500, null=True)),
                ('itemName01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item01')),
                ('itemName02', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.item02')),
                ('itemName03', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.item03')),
                ('langName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planguage')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('api.baseinfo', models.Model),
        ),
    ]
